[project]
name = "samp"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "datetime>=5.5",
    "openpyxl>=3.1.5",
    "pandas>=2.2.3",
    "pyinstaller>=6.13.0",
    "tkintertable>=1.3.3",
]
